---
- block:
    - set_fact:
        is_exists: false
    - name: "Pre check | projects"
      include_role:
        name: role_ansible_pre_check
      vars:
        category: "{{ category_name }}"
        task_name: "{{ project_name | urlencode}}"
        orgid: "{{ org }}"
        get_id_with_org: true

    - name: "set | task id"
      set_fact:
        project_id: "{{ pre_check_result.json.results[0].id }}"
        is_exists: true
      when: pre_check_result.json.results | count > 0

    - name: "Pre check | credentials"
      include_role:
        name: role_ansible_pre_check
      vars:
        category: "credentials"
        task_name: "{{ scm_creds | urlencode}}"
        orgid: "{{ org }}"
        get_id_with_org: true

    - name: "set | creds id when found"
      set_fact:
        creds_id: "{{ pre_check_result.json.results[0].id }}"
      when: pre_check_result.json.results | count > 0

    - name: "set | creds id when not found"
      set_fact:
        creds_id: ""
      when: pre_check_result.json.results | count == 0
   
    - name: "prepare | payload"
      set_fact:
        project_payload: { "name": "{{ project_name }}", "description": "{{ project_description }}", "organization": "{{ org }}", "scm_url": "{{ url }}", "scm_branch": "{{ branch }}", "scm_clean": true, "scm_delete_on_update": false, "credential": "{{ creds_id }}", "scm_type": "git" }
     
    - name: "PATCH | if project already exists"
      block:
        - name: "update the inv | using patch method"
          include_role:
            name: role_ansible_update_configurations
          vars:
            category: "projects"
            payload: "{{ project_payload }}"
            method: "PATCH"
            configuration_id: "{{ project_id }}"
      when: is_exists == true

    - name: "POST | create a new inv"
      block:
        - name: "create new inv | using POST method"
          include_role:
            name: role_ansible_create_configurations
          vars:
            category: "projects"
            payload: "{{ project_payload }}"
            method: "POST"
      when: is_exists == false
      
  rescue:
    - fail:
        msg: "Failed while creating inventory {{ project_name }}"
