---
- name: "create | git projects"
  include_tasks: create_projects_restapi.yml
  vars:
    project_name: "{{ project_data['git'][item | int]['name'] }}"
    project_description: "{{ project_data['git'][item | int]['description'] }}"
    org: "{{ org_id }}"
    branch: "{{ project_data['git'][item | int]['branch'] }}"
    url: "{{ project_data['git'][item | int]['url'] }}"
    scm_creds: "{{ project_data['git'][item | int]['credentials'] }}"
    category_name: "projects"
  with_sequence: start=0 end="{{ project_data['git'] | count | int -1 }}"