- block:
    - name: "create | credentials {{ creds_name }}"
      uri:
        url: "{{ tower_gui_url }}/api/v2/{{ category }}/"
        method: POST
        url_username: "{{ tower_gui_username }}"
        url_password: "{{ tower_gui_password }}"
        body_format: json
        body: "{{ pay_load }}"
        validate_certs: false
        force_basic_auth: true
        return_content: yes
        status_code: 201
      no_log: true
  rescue:
    - debug:
        msg: "Failed while creating credentials {{ creds_name }}"